---
title: "prob5cp2"
output: html_document
---

```{r, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

library(tidyverse)
library(here)
library(viridis)
library(broom)
library(modelr)
library(plotly)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = FALSE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r,message=FALSE, warning=FALSE}
dados = readr::read_csv(here::here("data/speed-dating2.csv"))
dados <- dados %>% filter(complete.cases(.))
dados <- dados %>% mutate(diferenca_idade = age_o - age) 
dados$diferenca_idade <- abs(dados$diferenca_idade/10)
dados <- dados %>% transform(attr3_s = as.numeric(attr3_s),
                             sinc3_s = as.numeric(sinc3_s),
                             intel3_s = as.numeric(intel3_s),
                             fun3_s = as.numeric(fun3_s),
                             amb3_s = as.numeric(amb3_s),
                             attr = as.numeric(attr),
                             sinc = as.numeric(sinc),
                             intel = as.numeric(intel),
                             fun = as.numeric(fun),
                             amb = as.numeric(amb))
dados <- dados %>% mutate(crush = (dados$amb + dados$fun + dados$attr + dados$intel + dados$sinc)/5)
dados <- dados %>% mutate(auto_estima = (dados$amb3_s + dados$fun3_s + dados$attr3_s + dados$intel3_s + dados$sinc3_s)/5)
dados <- dados %>% mutate(dec = ifelse(dec == "yes",1,0))
```

```{r}
bm <- glm(dec ~ crush + auto_estima, 
          data = dados, 
          family = "binomial")

tidy(bm, conf.int = TRUE) %>% 
  select(-statistic, -p.value)
# EXPONENCIANDO:
tidy(bm, conf.int = TRUE, exponentiate = TRUE) %>% 
  select(-statistic, -p.value)

```
